remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Analyzing Recipes on Food.com
description: Annie He || anniehe@umich.edu || EECS 398-003 - Practical Data Science
